services:
  app:
    image: node:20
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "5173:5173"
    networks:
      - proxy
    command: sh -c "npm install && npm run dev"

networks:
  proxy:
    external: true