version: '3.8'

services:
  react-app:
    build: .  
    container_name: react-container
    working_dir: /app
    volumes:
      - .:/app  
      - /app/node_modules  
    ports:
      - "5173:5173" 
    environment:
      - CHOKIDAR_USEPOLLING=true  